CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  email VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
   name VARCHAR(50) NOT NULL,
   CONSTRAINT pk_categories PRIMARY KEY (id),
   CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events (
   id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
   title VARCHAR(120) NOT NULL,
   description VARCHAR(7000) NOT NULL,
   annotation VARCHAR(2000) NOT NULL,
   category_id BIGINT NOT NULL,
   initiator_id BIGINT NOT NULL,
   lat DOUBLE PRECISION NOT NULL,
   lon DOUBLE PRECISION NOT NULL,
   created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   published_on TIMESTAMP WITHOUT TIME ZONE,
   paid BOOLEAN NOT NULL,
   participants_limit INTEGER NOT NULL,
   request_moderation BOOLEAN NOT NULL,
   state VARCHAR(10) NOT NULL,
   available BOOLEAN NOT NULL,
   CONSTRAINT pk_events PRIMARY KEY (id),
   CONSTRAINT fk_events_category_id_categories FOREIGN KEY (category_id) REFERENCES categories (id),
   CONSTRAINT fk_events_initiator_id_users FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
   id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
   event_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL,
   created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   status VARCHAR(10) NOT NULL,
   CONSTRAINT pk_requests PRIMARY KEY (id),
   CONSTRAINT fk_requests_event_id_events FOREIGN KEY (event_id) REFERENCES events (id),
   CONSTRAINT fk_requests_user_id_events FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
   id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
   text VARCHAR(5000) NOT NULL,
   author_id BIGINT NOT NULL,
   event_id BIGINT NOT NULL,
   created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   moderated TIMESTAMP WITHOUT TIME ZONE,
   edited TIMESTAMP WITHOUT TIME ZONE,
   status VARCHAR(10) NOT NULL,
   CONSTRAINT pk_comments PRIMARY KEY (id),
   CONSTRAINT fk_comments_event_id_events FOREIGN KEY (event_id) REFERENCES events (id),
   CONSTRAINT fk_comments_author_id_users FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilations (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   title VARCHAR(150) NOT NULL,
   pinned BOOLEAN NOT NULL,
   CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations_events (
   compilation_id BIGINT NOT NULL,
   event_id BIGINT NOT NULL,
   CONSTRAINT pk_compilations_events PRIMARY KEY (compilation_id, event_id),
   CONSTRAINT fk_compilations_events_compilation_id FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE,
   CONSTRAINT fk_compilations_events_event_id FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);
