CREATE TABLE hits (
   id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
   uri VARCHAR(1024) NOT NULL,
   timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   app VARCHAR(100) NOT NULL,
   ip VARCHAR(16) NOT NULL,
   CONSTRAINT pk_hits PRIMARY KEY (id)
);